name: MedievalMarkets
main: com.brandon.medievalmarkets.MedievalMarketsPlugin
version: 0.0.5
api-version: "1.21"

softdepend: [MPCBridge, BurgsAndBanners]

commands:
  markets:
    description: Open markets UI / commands
    usage: /markets
    permission: medievalmarkets.use
  market:
    description: Market commands
    usage: "/market <list|price|buy|sell>"
    permission: medievalmarkets.use

permissions:
  medievalmarkets.use:
    default: true
