name: MedievalMarkets
main: com.brandon.medievalmarkets.MedievalMarketsPlugin
version: 0.0.4
api-version: "1.21"

softdepend: [BurgsAndBanners]
            [MPCBridge]


commands:
  market:
    description: Central marketplace actions
    usage: /market
    aliases: [mkt]

permissions:
  medievalmarkets.admin:
    default: op
